### ISSUE TITLE
Not starting up on Ubuntu after installing

### ISSUE THREAD

**Issue by gerdneuman** [myTonino/Tonino-App#2]
I installed version 1.0.15 (see #1), but absolute nothing happens when it is started. No window, no output, nothing:

```
~$ cd /tmp/

/tmp$ sudo dpkg -i tonino-linux-1.0.15_i386.deb 
[sudo] Passwort für xxx: 
Vormals nicht ausgewähltes Paket tonino wird gewählt.
(Lese Datenbank ... 384941 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von tonino-linux-1.0.15_i386.deb ...
Entpacken von tonino (1.0.15) ...
tonino (1.0.15) wird eingerichtet ...
xdg-utils   1.1.1-1ubuntu1
Trigger für man-db (2.7.5-1) werden verarbeitet ...
Trigger für desktop-file-utils (0.22-1ubuntu5) werden verarbeitet ...
Trigger für mime-support (3.59ubuntu1) werden verarbeitet ...
Trigger für gnome-menus (3.13.3-6ubuntu3) werden verarbeitet ...
Trigger für bamfdaemon (0.5.3~bzr0+16.04.20160415-0ubuntu1) werden verarbeitet ...
Rebuilding /usr/share/applications/bamf-2.index...

/tmp$ tonino 
/tmp$ tonino 
/tmp$ tonino --help
/tmp$ tonino --version
/tmp$ time tonino 

real    0m0.593s
user    0m0.536s
sys 0m0.048s

```

There's no Tonino connected atm, but I would assume that there's some kind of empty window even if tonino is not yet connected. As said in #1 I would like to connect a Tonino for Cupping on Friday (14th Oct 2016)

**Comment by myTonino** [comment]
Hm. Nothing in any log? Could you please share the result of "ls -la /usr/share/tonino/"

Note that the purpose of the Tonino app is to configure the Tonino device and has not support for cupping of coffee.

**Comment by gerdneuman** [comment]
```
$ dmesg
[ 5698.812329] usb 6-2: new full-speed USB device number 2 using uhci_hcd
[ 5699.009073] usb 6-2: New USB device found, idVendor=0403, idProduct=6015
[ 5699.009085] usb 6-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 5699.009093] usb 6-2: Product: FT231X USB UART
[ 5699.009099] usb 6-2: Manufacturer: FTDI
[ 5699.009106] usb 6-2: SerialNumber: DJ00HV3O
[ 5700.062605] usbcore: registered new interface driver usbserial
[ 5700.062628] usbcore: registered new interface driver usbserial_generic
[ 5700.062648] usbserial: USB Serial support registered for generic
[ 5700.071986] usbcore: registered new interface driver ftdi_sio
[ 5700.072217] usbserial: USB Serial support registered for FTDI USB Serial Device
[ 5700.072295] ftdi_sio 6-2:1.0: FTDI USB Serial Device converter detected
[ 5700.072354] usb 6-2: Detected FT-X
[ 5700.075046] usb 6-2: FTDI USB Serial Device converter now attached to ttyUSB0



$ ls -la /usr/share/tonino/
insgesamt 114232
drwxr-xr-x   7 root root    24576 Okt 12 21:10 .
drwxr-xr-x 584 root root    24576 Okt 12 21:10 ..
-rw-r--r--   1 root root    32796 Okt 12 10:41 array.so
-rw-r--r--   1 root root    16592 Okt 12 10:41 binascii.so
-rw-r--r--   1 root root     7648 Okt 12 10:41 _bisect.so
-rw-r--r--   1 root root    29960 Okt 12 10:41 bz2.so
-rw-r--r--   1 root root   126880 Okt 12 10:41 _codecs_cn.so
-rw-r--r--   1 root root   140384 Okt 12 10:41 _codecs_hk.so
-rw-r--r--   1 root root    16096 Okt 12 10:41 _codecs_iso2022.so
-rw-r--r--   1 root root   223328 Okt 12 10:41 _codecs_jp.so
-rw-r--r--   1 root root   119360 Okt 12 10:41 _codecs_kr.so
-rw-r--r--   1 root root    94304 Okt 12 10:41 _codecs_tw.so
-rw-r--r--   1 root root    24192 Okt 12 10:41 _collections.so
-rw-r--r--   1 root root    66596 Okt 12 10:41 cPickle.so
-rw-r--r--   1 root root    17156 Okt 12 10:41 cStringIO.so
-rw-r--r--   1 root root    24388 Okt 12 10:41 _csv.so
-rw-r--r--   1 root root   129832 Okt 12 10:41 _ctypes.so
-rw-r--r--   1 root root    66428 Okt 12 10:41 _curses.so
-rw-r--r--   1 root root    68656 Okt 12 10:41 datetime.so
-rw-r--r--   1 root root    13616 Okt 12 10:41 fcntl.so
-rw-r--r--   1 root root     8840 Okt 12 10:41 _functools.so
-rw-r--r--   1 root root     5056 Okt 12 10:41 future_builtins.so
-rw-r--r--   1 root root    66476 Okt 12 10:41 gnome-keyring-pkcs11.so
-rw-r--r--   1 root root     6888 Okt 12 10:41 grp.so
-rw-r--r--   1 root root    15920 Okt 12 10:41 _hashlib.so
-rw-r--r--   1 root root    17152 Okt 12 10:41 _heapq.so
drwxr-xr-x   2 root root     4096 Okt 12 21:10 icons
drwxr-xr-x   3 root root     4096 Okt 12 21:10 includes
-rw-r--r--   1 root root   130840 Okt 12 10:41 _io.so
-rw-r--r--   1 root root    42848 Okt 12 10:41 itertools.so
-rw-r--r--   1 root root    32212 Okt 12 10:41 _json.so
-rw-r--r--   1 root root   320200 Okt 12 10:41 libblas.so.3
-rw-r--r--   1 root root    70464 Okt 12 10:41 libbz2.so.1
-rw-r--r--   1 root root    13836 Okt 12 10:41 libcom_err.so.2
-rw-r--r--   1 root root  1849944 Okt 12 10:41 libcrypto.so.10
-rw-r--r--   1 root root   622860 Okt 12 10:41 libfreetype.so.6
-rw-r--r--   1 root root   120672 Okt 12 10:41 libgcc_s.so.1
-rw-r--r--   1 root root   872472 Okt 12 10:41 libgfortran.so.3
-rw-r--r--   1 root root   262124 Okt 12 10:41 libgssapi_krb5.so.2
-rw-r--r--   1 root root 16011840 Okt 12 10:41 libicudata.so.42
-rw-r--r--   1 root root  1824112 Okt 12 10:41 libicui18n.so.42
-rw-r--r--   1 root root  1407268 Okt 12 10:41 libicuuc.so.42
-rw-r--r--   1 root root   169712 Okt 12 10:41 libk5crypto.so.3
-rw-r--r--   1 root root     9536 Okt 12 10:41 libkeyutils.so.1
-rw-r--r--   1 root root   901552 Okt 12 10:41 libkrb5.so.3
-rw-r--r--   1 root root    42716 Okt 12 10:41 libkrb5support.so.0
-rw-r--r--   1 root root  4684156 Okt 12 10:41 liblapack.so.3
-rw-r--r--   1 root root   195244 Okt 12 10:41 libncursesw.so.5
-rw-r--r--   1 root root   158736 Okt 12 10:41 libpng12.so.0
-rw-r--r--   1 root root  5751572 Okt 12 10:41 libQt5Core.so.5
-rw-r--r--   1 root root   499636 Okt 12 10:41 libQt5DBus.so.5
-rw-r--r--   1 root root  4480668 Okt 12 10:41 libQt5Gui.so.5
-rw-r--r--   1 root root   390172 Okt 12 10:41 libQt5PrintSupport.so.5
-rw-r--r--   1 root root   341976 Okt 12 10:41 libQt5Svg.so.5
-rw-r--r--   1 root root  6407352 Okt 12 10:41 libQt5Widgets.so.5
-rw-r--r--   1 root root   247332 Okt 12 10:41 libQt5Xml.so.5
-rwxr-xr-x   3 root root  7374286 Okt 12 10:41 library.zip
-rw-r--r--   1 root root   233652 Okt 12 10:41 libreadline.so.6
-rw-r--r--   1 root root   120784 Okt 12 10:41 libselinux.so.1
-rw-r--r--   1 root root   420428 Okt 12 10:41 libssl.so.10
-rw-r--r--   1 root root   930192 Okt 12 10:41 libstdc++.so.6
-rw-r--r--   1 root root    98120 Okt 12 10:41 libtinfo.so.5
-rw-r--r--   1 root root  1277184 Okt 12 10:41 libX11.so.6
-rw-r--r--   1 root root     8516 Okt 12 10:41 libXau.so.6
-rw-r--r--   1 root root   129204 Okt 12 10:41 libxcb.so.1
-rw-r--r--   1 root root    68716 Okt 12 10:41 libXext.so.6
-rw-r--r--   1 root root  1388108 Okt 12 10:41 libxml2.so.2
-rw-r--r--   1 root root    75384 Okt 12 10:41 libz.so.1
-rwxr-xr-x   1 root root    35821 Okt 12 10:41 LICENSE.txt
-rw-r--r--   1 root root    15776 Okt 12 10:41 _locale.so
-rw-r--r--   1 root root    26704 Okt 12 10:41 math.so
-rw-r--r--   1 root root   347580 Okt 12 10:41 matplotlib.backends._backend_agg.so
-rw-r--r--   1 root root    19856 Okt 12 10:41 matplotlib._cntr.so
-rw-r--r--   1 root root    52976 Okt 12 10:41 matplotlib._contour.so
-rw-r--r--   1 root root    73604 Okt 12 10:41 matplotlib.ft2font.so
-rw-r--r--   1 root root   134224 Okt 12 10:41 matplotlib._image.so
-rw-r--r--   1 root root   177756 Okt 12 10:41 matplotlib._path.so
-rw-r--r--   1 root root    20324 Okt 12 10:41 matplotlib._png.so
-rw-r--r--   1 root root   340156 Okt 12 10:41 matplotlib._qhull.so
-rw-r--r--   1 root root   109584 Okt 12 10:41 matplotlib._tri.so
-rw-r--r--   1 root root    57100 Okt 12 10:41 matplotlib.ttconv.so
-rw-r--r--   1 root root    17616 Okt 12 10:41 mmap.so
drwxr-xr-x   6 root root     4096 Okt 12 21:10 mpl-data
-rw-r--r--   1 root root    24880 Okt 12 10:41 _multibytecodec.so
-rw-r--r--   1 root root    19760 Okt 12 10:41 _multiprocessing.so
-rw-r--r--   1 root root     2832 Okt 12 10:41 numpy.core._dummy.so
-rw-r--r--   1 root root  1473776 Okt 12 10:41 numpy.core.multiarray.so
-rw-r--r--   1 root root    55984 Okt 12 10:41 numpy.core.multiarray_tests.so
-rw-r--r--   1 root root     5760 Okt 12 10:41 numpy.core.operand_flag_tests.so
-rw-r--r--   1 root root     5708 Okt 12 10:41 numpy.core.struct_ufunc_test.so
-rw-r--r--   1 root root    40408 Okt 12 10:41 numpy.core.test_rational.so
-rw-r--r--   1 root root   572276 Okt 12 10:41 numpy.core.umath.so
-rw-r--r--   1 root root    11364 Okt 12 10:41 numpy.core.umath_tests.so
-rw-r--r--   1 root root    31248 Okt 12 10:41 numpy.fft.fftpack_lite.so
-rw-r--r--   1 root root    10688 Okt 12 10:41 numpy.linalg.lapack_lite.so
-rw-r--r--   1 root root   114120 Okt 12 10:41 numpy.linalg._umath_linalg.so
-rw-r--r--   1 root root   701768 Okt 12 10:41 numpy.random.mtrand.so
-rw-r--r--   1 root root    28516 Okt 12 10:41 operator.so
-rw-r--r--   1 root root    49308 Okt 12 10:41 parser.so
-rwxr-xr-x   3 root root  7374286 Okt 12 10:41 py
-rw-r--r--   1 root root   195616 Okt 12 10:41 pyexpat.so
-rw-r--r--   1 root root  2372108 Okt 12 10:41 PyQt4.QtCore.so
-rw-r--r--   1 root root   208932 Okt 12 10:41 PyQt4.QtDBus.so
-rw-r--r--   1 root root  7479400 Okt 12 10:41 PyQt4.QtGui.so
-rw-r--r--   1 root root    97896 Okt 12 10:41 PyQt4.QtSvg.so
-rw-r--r--   1 root root   312576 Okt 12 10:41 PyQt4.QtXml.so
-rw-r--r--   1 root root  2231420 Okt 12 10:41 PyQt5.QtCore.so
-rw-r--r--   1 root root   178608 Okt 12 10:41 PyQt5.QtDBus.so
-rw-r--r--   1 root root  1973284 Okt 12 10:41 PyQt5.QtGui.so
-rw-r--r--   1 root root   186968 Okt 12 10:41 PyQt5.QtPrintSupport.so
-rw-r--r--   1 root root    77196 Okt 12 10:41 PyQt5.QtSvg.so
-rw-r--r--   1 root root  4264340 Okt 12 10:41 PyQt5.QtWidgets.so
-rw-r--r--   1 root root   246908 Okt 12 10:41 PyQt5.QtXml.so
-rw-r--r--   1 root root   106568 Okt 12 10:41 pyserial-3.1a0-py2.7.egg
-rwxr-xr-x   1 root root       39 Okt 12 10:41 qt.conf
-rw-r--r--   1 root root    10448 Okt 12 10:41 _random.so
-rw-r--r--   1 root root    18048 Okt 12 10:41 readline.so
-rwxr-xr-x   1 root root     5155 Okt 12 10:41 README.txt
drwxr-xr-x   3 root root     4096 Okt 11 10:47 Resources
-rw-r--r--   1 root root    80292 Okt 12 10:41 scipy.integrate._dop.so
-rw-r--r--   1 root root   145480 Okt 12 10:41 scipy.integrate.lsoda.so
-rw-r--r--   1 root root   133432 Okt 12 10:41 scipy.integrate._odepack.so
-rw-r--r--   1 root root    98936 Okt 12 10:41 scipy.integrate._quadpack.so
-rw-r--r--   1 root root   161344 Okt 12 10:41 scipy.integrate.vode.so
-rw-r--r--   1 root root   359748 Okt 12 10:41 scipy.interpolate.dfitpack.so
-rw-r--r--   1 root root   192304 Okt 12 10:41 scipy.interpolate._fitpack.so
-rw-r--r--   1 root root   268872 Okt 12 10:41 scipy.interpolate.interpnd.so
-rw-r--r--   1 root root   283816 Okt 12 10:41 scipy.interpolate._ppoly.so
-rw-r--r--   1 root root   207368 Okt 12 10:41 scipy.linalg.cython_blas.so
-rw-r--r--   1 root root   610300 Okt 12 10:41 scipy.linalg.cython_lapack.so
-rw-r--r--   1 root root   265160 Okt 12 10:41 scipy.linalg._decomp_update.so
-rw-r--r--   1 root root   321732 Okt 12 10:41 scipy.linalg._fblas.so
-rw-r--r--   1 root root   751876 Okt 12 10:41 scipy.linalg._flapack.so
-rw-r--r--   1 root root    50276 Okt 12 10:41 scipy.linalg._flinalg.so
-rw-r--r--   1 root root   178984 Okt 12 10:41 scipy.linalg._solve_toeplitz.so
-rw-r--r--   1 root root   101732 Okt 12 10:41 scipy.optimize._cobyla.so
-rw-r--r--   1 root root   139016 Okt 12 10:41 scipy.optimize._group_columns.so
-rw-r--r--   1 root root   107044 Okt 12 10:41 scipy.optimize._lbfgsb.so
-rw-r--r--   1 root root   114472 Okt 12 10:41 scipy.optimize._lsq.givens_elimination.so
-rw-r--r--   1 root root    32868 Okt 12 10:41 scipy.optimize.minpack2.so
-rw-r--r--   1 root root    84448 Okt 12 10:41 scipy.optimize._minpack.so
-rw-r--r--   1 root root    27584 Okt 12 10:41 scipy.optimize.moduleTNC.so
-rw-r--r--   1 root root    35972 Okt 12 10:41 scipy.optimize._nnls.so
-rw-r--r--   1 root root    77280 Okt 12 10:41 scipy.optimize._slsqp.so
-rw-r--r--   1 root root     8496 Okt 12 10:41 scipy.optimize._zeros.so
-rw-r--r--   1 root root   143496 Okt 12 10:41 scipy.sparse.csgraph._min_spanning_tree.so
-rw-r--r--   1 root root   263880 Okt 12 10:41 scipy.sparse.csgraph._reordering.so
-rw-r--r--   1 root root   218620 Okt 12 10:41 scipy.sparse.csgraph._shortest_path.so
-rw-r--r--   1 root root   134752 Okt 12 10:41 scipy.sparse.csgraph._tools.so
-rw-r--r--   1 root root   117752 Okt 12 10:41 scipy.sparse.csgraph._traversal.so
-rw-r--r--   1 root root   416872 Okt 12 10:41 scipy.sparse._csparsetools.so
-rw-r--r--   1 root root   308080 Okt 12 10:41 scipy.sparse.linalg.dsolve._superlu.so
-rw-r--r--   1 root root   555220 Okt 12 10:41 scipy.sparse.linalg.eigen.arpack._arpack.so
-rw-r--r--   1 root root   205156 Okt 12 10:41 scipy.sparse.linalg.isolve._iterative.so
-rw-r--r--   1 root root  4095564 Okt 12 10:41 scipy.sparse._sparsetools.so
-rw-r--r--   1 root root   491516 Okt 12 10:41 scipy.spatial.ckdtree.so
-rw-r--r--   1 root root    64580 Okt 12 10:41 scipy.spatial._distance_wrap.so
-rw-r--r--   1 root root   779708 Okt 12 10:41 scipy.spatial.qhull.so
-rw-r--r--   1 root root    19464 Okt 12 10:41 scipy.special._comb.so
-rw-r--r--   1 root root    61676 Okt 12 10:41 scipy.special._ellip_harm_2.so
-rw-r--r--   1 root root   591076 Okt 12 10:41 scipy.special.specfun.so
-rw-r--r--   1 root root    82024 Okt 12 10:41 scipy.special._ufuncs_cxx.so
-rw-r--r--   1 root root  1254668 Okt 12 10:41 scipy.special._ufuncs.so
-rw-r--r--   1 root root    61808 Okt 12 10:41 scipy.stats.mvn.so
-rw-r--r--   1 root root    36596 Okt 12 10:41 scipy.stats.statlib.so
-rw-r--r--   1 root root   151944 Okt 12 10:41 scipy.stats._stats.so
-rw-r--r--   1 root root    19204 Okt 12 10:41 select.so
-rw-r--r--   1 root root    90360 Okt 12 10:41 sip.so
-rw-r--r--   1 root root    67664 Okt 12 10:41 _socket.so
-rw-r--r--   1 root root    74568 Okt 12 10:41 _ssl.so
-rw-r--r--   1 root root    20960 Okt 12 10:41 strop.so
-rw-r--r--   1 root root    27716 Okt 12 10:41 _struct.so
-rw-r--r--   1 root root    14864 Okt 12 10:41 termios.so
-rw-r--r--   1 root root    16560 Okt 12 10:41 time.so
-rwxr-xr-x   3 root root  7374286 Okt 12 10:41 tonino
-rwxr-xr-x   1 root root      236 Okt 12 10:41 tonino-toni.xml
-rw-r--r--   1 root root     3316 Okt 12 10:41 tornado.speedups.so
drwxr-xr-x   2 root root     4096 Okt 12 21:10 translations
-rw-r--r--   1 root root   684932 Okt 12 10:41 unicodedata.so
-rw-r--r--   1 root root    19008 Okt 12 10:41 zlib.so
```

Tested with the latest version (since #1 has been fixed now)

**Comment by myTonino** [comment]
So still not working. I don't see any error message. Installation looks ok. Anything in /var/log/syslog on start? Could you try to start that thing via

`# /usr/share/tonino/tonino`

Maybe it is a problem with some rights, try

`# sudo /usr/share/tonino/tonino`

What are the messages in the terminal on those commands?

**Comment by myTonino** [comment]
Closed due to lack of further input
